# Generated by Django 3.2 on 2021-04-16 02:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tools', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='media/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['.mp4, .mov'])])),
                ('video_upload_timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annotation_text', models.CharField(max_length=200)),
                ('annotation_detail', models.CharField(max_length=400)),
                ('annotation_start_time', models.DateTimeField()),
                ('annotation_duration', models.DurationField(blank=True)),
                ('annotation_tools', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='annotation.tools')),
                ('annotation_video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotation.video')),
            ],
        ),
    ]
