# Generated by Django 3.2 on 2021-04-16 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0003_auto_20210416_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_upload_timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
