# Generated by Django 3.2 on 2021-05-01 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0004_alter_video_video_upload_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotation',
            name='annotation_start_time',
        ),
        migrations.AddField(
            model_name='annotation',
            name='annotation_timestamp',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_upload_timestamp',
            field=models.DateTimeField(),
        ),
    ]
