# Generated by Django 3.2 on 2021-05-01 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0005_auto_20210501_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_upload_timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
