# Generated by Django 3.2 on 2021-05-01 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0006_alter_video_video_upload_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='annotation_timestamp',
            field=models.IntegerField(null=True),
        ),
    ]
