# Generated by Django 3.2 on 2021-05-03 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0007_alter_annotation_annotation_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='annotation_video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='annotation.video'),
        ),
        migrations.AddField(
            model_name='tools',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='annotation.video'),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='annotation_timestamp',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='tools',
            name='tools',
            field=models.TextField(),
        ),
    ]
