# Generated by Django 3.2 on 2021-05-01 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0007_alter_annotation_annotation_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='annotation_timestamp',
            field=models.FloatField(null=True),
        ),
    ]
