# Generated by Django 3.2 on 2021-05-04 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0009_remove_video_video_upload_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_timestamp',
            field=models.FloatField(null=True),
        ),
    ]
