# Generated by Django 3.2 on 2021-05-05 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0010_video_video_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='annotation_tool',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='tools',
            name='tools_file',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='tools',
            name='tools',
            field=models.CharField(max_length=1000),
        ),
    ]
