# Generated by Django 3.2 on 2021-05-05 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0011_auto_20210505_1522'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tools',
            old_name='video',
            new_name='tools_video',
        ),
    ]
