# Generated by Django 3.2 on 2021-05-06 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0013_alter_tools_tools'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='annotation_video_indicator',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tools',
            name='tools_video_indicator',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tools',
            name='tools_file',
            field=models.FileField(null=True, upload_to='tools'),
        ),
    ]
