# Generated by Django 3.2 on 2021-05-06 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0014_auto_20210506_0403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotation',
            name='annotation_detail',
        ),
    ]
