# Generated by Django 3.2 on 2021-05-07 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0015_remove_annotation_annotation_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='annotation_segment_end_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='annotation',
            name='annotation_type',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
