# Generated by Django 3.2 on 2021-05-08 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0016_auto_20210507_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotation',
            name='annotation_segment_end_time',
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='annotation_type',
        ),
        migrations.CreateModel(
            name='SegmentAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment_annotation_tool', models.CharField(blank=True, max_length=200)),
                ('segment_annotation_text', models.CharField(blank=True, max_length=200)),
                ('segment_annotation_timestamp', models.FloatField(null=True)),
                ('segment_annotation_video_indicator', models.CharField(blank=True, max_length=200, null=True)),
                ('segment_annotation_video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='annotation.video')),
            ],
        ),
        migrations.CreateModel(
            name='PointAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_annotation_tool', models.CharField(blank=True, max_length=200)),
                ('point_annotation_text', models.CharField(blank=True, max_length=200)),
                ('point_annotation_timestamp', models.FloatField(null=True)),
                ('point_annotation_video_indicator', models.CharField(blank=True, max_length=200, null=True)),
                ('point_annotation_video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='annotation.video')),
            ],
        ),
    ]
