# Generated by Django 3.2 on 2021-05-09 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0018_auto_20210509_0013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='segmentannotation',
            old_name='egment_annotation_endtime',
            new_name='segment_annotation_endtime',
        ),
    ]
